# CLA-EP boundary from the MERSCOPE data
cla.ep.boundary <- data.frame(mouse = c("m1471",
                                        "m1474", "m1474",
                                        "m1477", "m1477",
                                        "m1481", "m1481",
                                        "m1482", "m1482",
                                        "m1522", "m1522",
                                        "m88799", "m88799",
                                        "m88833",
                                        "m88833"),
                              level = c(44,
                                        44, 44,
                                        44, 44,
                                        44, 44,
                                        44, 44,
                                        44, 44,
                                        44, 44,
                                        53,
                                        68),
                              cla_side = c("CLA.2",
                                           "CLA.1", "CLA.2",
                                           "CLA.1", "CLA.2",
                                           "CLA.1", "CLA.2",
                                           "CLA.1", "CLA.2",
                                           "CLA.1", "CLA.2",
                                           "CLA.1", "CLA.2",
                                           "CLA.2",
                                           "CLA.2"),
                              boundary_type = c("CLA/EP",
                                                "CLA/EP", "CLA/EP",
                                                "CLA/EP", "CLA/EP",
                                                "CLA/EP", "CLA/EP",
                                                "CLA/EP", "CLA/EP",
                                                "CLA/EP", "CLA/EP",
                                                "CLA/EP", "CLA/EP",
                                                "CLA/EP",
                                                "CLA-like L6/CLA-EP"),
                              boundary = c(-650,
                                           -640, -710,
                                           540, 700,
                                           4220, 4290,
                                           -1070, -1100,
                                           -3250, -3230,
                                           -1550, -1360,
                                           -2130,
                                           -3850))
